### ISSUE TITLE
Heatmap error

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#22]
Testing latest version from this morning. I loaded E-MTAB-4888, did DE on recommend k=9, then picked Heatmap in pulldown.
![Screen Shot 2019-09-10 at 12 42 58 PM](https://user-images.githubusercontent.com/1418193/64645005-c8f61080-d3c8-11e9-85e7-a4f5d80121c0.png)

**Comment by AlexanderPico** [comment]
Here's task history. Did not have running from console...
![Screen Shot 2019-09-10 at 12 45 48 PM](https://user-images.githubusercontent.com/1418193/64645100-fc389f80-d3c8-11e9-9a9e-4e39377a96e3.png)

**Comment by scootermorris** [comment]
Hmmm....I'm not able to reproduce (although I do see a different problem).  Can you try to reproduce this when running on the console?

**Comment by AlexanderPico** [comment]
Will try now.  By the way, the heatmap on an individual network worked fine.

**Comment by AlexanderPico** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 27632
	at edu.ucsf.rbvi.scNetViz.internal.tasks.HeatMapTask.run(HeatMapTask.java:131) ~[?:?]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337) ~[87:org.cytoscape.work-swing-impl:3.7.1]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352) [87:org.cytoscape.work-swing-impl:3.7.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
java.lang.ArrayIndexOutOfBoundsException: 27632
	at edu.ucsf.rbvi.scNetViz.internal.tasks.HeatMapTask.run(HeatMapTask.java:131)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by scootermorris** [comment]
Hi Alex,
   I should have noticed earlier, but you have an old jar (your DE tab isn't the current one).  Can you download the latest jar from the repo and try again?

**Comment by AlexanderPico** [comment]
Ah, I did `git pull` but then copied the one from `target/` (from the last time I built it) rather than the one from the top level. User error!
