### ISSUE TITLE
Frozen Experiments Table

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/scNetViz#6]
If I load an experiment via commands, showTable is true by default and the table pops up just fine, but it is frozen. I can click on table rows, but not on the tabs or settings.

Fetching JSON from: https://www.ebi.ac.uk/gxa/sc/json/experiments
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.ucsf.rbvi.scNetViz.internal.model.SimpleMatrix.getColumnLabel(SimpleMatrix.java:90)
	at edu.ucsf.rbvi.scNetViz.internal.sources.gxa.GXACluster$GXAClusterTableModel.getColumnName(GXACluster.java:315)
	at javax.swing.JTable.addColumn(JTable.java:2804)
	at javax.swing.JTable.createDefaultColumnsFromModel(JTable.java:1290)
	at javax.swing.JTable.tableChanged(JTable.java:4392)
	at edu.ucsf.rbvi.scNetViz.internal.view.SimpleTable.tableChanged(SimpleTable.java:90)
	at javax.swing.JTable.setModel(JTable.java:3694)
	at javax.swing.JTable.<init>(JTable.java:635)
	at javax.swing.JTable.<init>(JTable.java:576)
	at edu.ucsf.rbvi.scNetViz.internal.view.SimpleTable.<init>(SimpleTable.java:35)
	at edu.ucsf.rbvi.scNetViz.internal.view.CategoriesTab.getCategoryTable(CategoriesTab.java:333)
	at edu.ucsf.rbvi.scNetViz.internal.view.CategoriesTab.init(CategoriesTab.java:315)
	at edu.ucsf.rbvi.scNetViz.internal.view.CategoriesTab.<init>(CategoriesTab.java:86)
	at edu.ucsf.rbvi.scNetViz.internal.tasks.ShowExperimentTableTask$1.run(ShowExperimentTableTask.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by RBVI** [comment]
OK, fixed.
